#!/bin/bash

# Update package lists
sudo apt-get update

# Install Nmap
sudo apt-get install -y nmap

# Install Wireshark
sudo apt-get install -y wireshark

# Install Metasploit
sudo apt-get install -y metasploit-framework

# Install Hashcat
sudo apt-get install -y hashcat

# Install SpiderFoot
sudo apt-get install -y spiderfoot

# Install Sliver
sudo apt-get install -y sliver-framework

# Install Burp Suite
sudo apt-get install -y burpsuite

# Install ProxyChains
sudo apt-get install -y proxychains4
